Improve deployment script for zero downtime and update API message

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -53,55 +53,53 @@ jobs:
             echo "Installing Docker..."
             sudo dnf install docker -y || true
 
-            echo "Starting Docker..." 
+            echo "Starting Docker..."
             sudo systemctl start docker
-
-            echo "Enabling Docker on boot..."
-            sudo systemctl enable docker
 
             echo "Pulling latest image..."
             docker pull ${{ secrets.DOCKER_USERNAME }}/node-api:latest
 
+            echo "Cleaning previous GREEN container..."
+            docker stop node-api-green || true
+            docker rm node-api-green || true
+
             echo "Starting new container (GREEN)..."
+            docker run -d -p 3001:3000 --name node-api-green \
+            ${{ secrets.DOCKER_USERNAME }}/node-api:latest
 
-            docker run -d -p 3001:3000 --name node-api-green ${{ secrets.DOCKER_USERNAME }}/node-api:latest
+            if [ $? -ne 0 ]; then
+              echo "Container start failed → rollback"
+              exit 1
+            fi
+
             echo "Waiting for container..."
-
             sleep 5
 
             echo "Health check..."
-
             if curl -f http://localhost:3001
             then
 
-              echo "New container healthy → switching traffic"
+              echo "Switching Nginx traffic..."
 
               sudo sed -i 's/localhost:3000/localhost:3001/' /etc/nginx/conf.d/node-api.conf
 
-              echo "Testing nginx configuration"
-              sudo nginx -t   
-
-              echo "Reloading nginx"
+              sudo nginx -t
               sudo systemctl reload nginx
 
-              echo "Stopping old container"
-
+              echo "Stopping old container..."
               docker stop node-api || true
-
-              echo "Removing old container"
               docker rm node-api || true
 
-              echo "Renaming new container to node-api"
+              echo "Renaming new container..."
               docker rename node-api-green node-api
 
             else
-              
-              echo "Deployment failed → rollback"
 
-              echo "Stopping new container"
+              echo "Health check failed → rollback"
+
               docker stop node-api-green
-
-              echo "Removing new container"
               docker rm node-api-green
+
+              exit 1
 
             fi
