CI CD in the Compose remove

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -11,10 +11,10 @@ jobs:
 
     steps:
 
-      - name: Checkout Code
+      - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Deploy to EC2
+      - name: Deploy to EC2 Server
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.EC2_HOST }}
@@ -23,47 +23,46 @@ jobs:
 
           script: |
 
-            echo "Updating system packages"
+            echo "Updating packages..."
             sudo dnf update -y
 
-            echo "Installing git if missing"
+            echo "Installing Git if missing..."
             if ! command -v git &> /dev/null
             then
               sudo dnf install git -y
             fi
 
-            echo "Installing docker if missing"
+            echo "Installing Docker if missing..."
             if ! command -v docker &> /dev/null
             then
               sudo dnf install docker -y
               sudo systemctl start docker
               sudo systemctl enable docker
-              sudo usermod -aG docker ec2-user
             fi
 
-            echo "Installing docker-compose if missing"
-            if ! command -v docker-compose &> /dev/null
-            then
-              sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
-              -o /usr/local/bin/docker-compose
-
-              sudo chmod +x /usr/local/bin/docker-compose
-            fi
-
-            echo "Cloning repo if not exists"
+            echo "Cloning repository if it does not exist..."
             if [ ! -d "backend-docker" ]; then
               git clone https://github.com/virugamacoder/backend-docker.git
             fi
 
             cd backend-docker
 
-            echo "Pull latest code"
+            echo "Pulling latest code..."
             git pull origin main
 
-            echo "Stopping old containers"
-            docker-compose down || true
+            echo "Stopping old container..."
+            docker stop node-api || true
 
-            echo "Building and starting containers"
-            docker-compose up -d --build
+            echo "Removing old container..."
+            docker rm node-api || true
 
-            echo "Deployment completed"
+            echo "Removing old image..."
+            docker rmi node-api || true
+
+            echo "Building new Docker image..."
+            docker build -t node-api .
+
+            echo "Starting new container..."
+            docker run -d -p 3000:3000 --name node-api node-api
+
+            echo "Deployment completed successfully!"
